export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:$PATH"
export PATH="/usr/sbin:$HOME/.local/bin:$HOME/dotfiles/scripts:$PATH"
export PATH="$HOME/.local/share/JetBrains/Toolbox/bin:/opt/viber:$PATH"
export PATH="$HOME/.cabal/bin:$PATH"

export MANPATH="/usr/local/man:$MANPATH"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Not sure if these are needed anymore...
export TERM="xterm-256color"
export ZSH_TMUX_FIXTERM=false
export ZSH_TMUX_AUTOSTART=true

# FZF!
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!*/.git/*" --glob "!*/target/*"'
export FZF_DEFAULT_OPTS='--reverse --inline-info'

# VirtualEnv
#export WORKON_HOME=$HOME/.virtualenvs
#export PROJECT_HOME=/vagrant

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Aliases
alias zshconfig="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias vi="nvim"
alias vim="nvim"
alias gvim="nvim"
alias tmux="tmux -2"

source $HOME/.env
