# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bureau"

# Set to this to use case-sensitive completion
#CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
#DISABLE_UPDATE_PROMPT=true

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
#DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse tmux)
plugins=(git)

# User configuration
if [ -f "$HOME/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh" ]; then
  source "$HOME/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh";
fi;
source $ZSH/oh-my-zsh.sh

# VirtualEnv
#source /usr/local/bin/virtualenvwrapper.sh

# TODO: fix this
#eval "$(stack --bash-completion-script stack)"

source ~/dotfiles/scripts/z.sh

# Change Capslock to Escape
xmodmap $HOME/dotfiles/config/xmodmap-esc

# Disable touchpad
/bin/bash $HOME/dotfiles/scripts/disable_touchpad.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
